import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields


SUBCONTRACT_DEPENDS = "eval:doc.is_subcontracted==1"


def execute():
    """Add Orden de Manufactura tab on subcontracted Purchase Orders."""
    create_custom_fields(
        {
            "Purchase Order": [
                {
                    "fieldname": "om_tab_orden_manufactura",
                    "label": "Orden de Manufactura",
                    "fieldtype": "Tab Break",
                    "insert_after": "connections_tab",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_section_info_general",
                    "label": "Info General",
                    "fieldtype": "Section Break",
                    "insert_after": "om_tab_orden_manufactura",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_fecha_requerida",
                    "label": "Fecha requerida",
                    "fieldtype": "Date",
                    "insert_after": "om_section_info_general",
                    "read_only": 1,
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_column_info_general",
                    "fieldtype": "Column Break",
                    "insert_after": "om_fecha_requerida",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_bordado",
                    "label": "Bordado",
                    "fieldtype": "Check",
                    "insert_after": "om_column_info_general",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_estampado",
                    "label": "Estampado",
                    "fieldtype": "Check",
                    "insert_after": "om_bordado",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_sublimado",
                    "label": "Sublimado",
                    "fieldtype": "Check",
                    "insert_after": "om_estampado",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_reflejante",
                    "label": "Reflejante",
                    "fieldtype": "Check",
                    "insert_after": "om_sublimado",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_aberturas",
                    "label": "Aberturas",
                    "fieldtype": "Int",
                    "insert_after": "om_reflejante",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_section_detallada",
                    "label": "Informacion mas detallada",
                    "fieldtype": "Section Break",
                    "insert_after": "om_aberturas",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_modelo",
                    "label": "Modelo",
                    "fieldtype": "Data",
                    "insert_after": "om_section_detallada",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_tela",
                    "label": "Tela",
                    "fieldtype": "Data",
                    "insert_after": "om_modelo",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_color_principal",
                    "label": "Color Principal",
                    "fieldtype": "Data",
                    "insert_after": "om_tela",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_column_detallada",
                    "fieldtype": "Column Break",
                    "insert_after": "om_color_principal",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_combinacion",
                    "label": "Combinacion",
                    "fieldtype": "Small Text",
                    "insert_after": "om_column_detallada",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_color",
                    "label": "Color",
                    "fieldtype": "Data",
                    "insert_after": "om_combinacion",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_forro",
                    "label": "Forro",
                    "fieldtype": "Data",
                    "insert_after": "om_color",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_ubicacion",
                    "label": "Ubicacion",
                    "fieldtype": "Small Text",
                    "insert_after": "om_forro",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_section_tallas_caballero",
                    "label": "Tabla 1 (Tallas Caballero)",
                    "fieldtype": "Section Break",
                    "insert_after": "om_ubicacion",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_prendas_caballero_total",
                    "label": "Prendas (Total)",
                    "fieldtype": "Int",
                    "insert_after": "om_section_tallas_caballero",
                    "read_only": 1,
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_tallas_caballero",
                    "label": "Tallas Caballero",
                    "fieldtype": "Table",
                    "options": "Orden Manufactura Talla Caballero",
                    "insert_after": "om_prendas_caballero_total",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_section_tallas_dama",
                    "label": "Tabla 2 (Tallas Dama)",
                    "fieldtype": "Section Break",
                    "insert_after": "om_tallas_caballero",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_prendas_dama_total",
                    "label": "Prendas (Total)",
                    "fieldtype": "Int",
                    "insert_after": "om_section_tallas_dama",
                    "read_only": 1,
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_tallas_dama",
                    "label": "Tallas Dama",
                    "fieldtype": "Table",
                    "options": "Orden Manufactura Talla Dama",
                    "insert_after": "om_prendas_dama_total",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_section_procesos",
                    "label": "Tabla de procesos",
                    "fieldtype": "Section Break",
                    "insert_after": "om_tallas_dama",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_procesos",
                    "label": "Procesos",
                    "fieldtype": "Table",
                    "options": "Orden Manufactura Proceso",
                    "insert_after": "om_section_procesos",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_section_observaciones",
                    "label": "Observaciones",
                    "fieldtype": "Section Break",
                    "insert_after": "om_procesos",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_observaciones",
                    "label": "Observaciones",
                    "fieldtype": "Small Text",
                    "insert_after": "om_section_observaciones",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_section_tablas_flexibles",
                    "label": "Tablas de medidas y equivalencias",
                    "fieldtype": "Section Break",
                    "insert_after": "om_observaciones",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_tablas_flexibles",
                    "label": "Tablas Flexibles",
                    "fieldtype": "Table",
                    "options": "Orden Manufactura Tabla Flexible",
                    "insert_after": "om_section_tablas_flexibles",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_section_archivos",
                    "label": "Diagramas y archivos",
                    "fieldtype": "Section Break",
                    "insert_after": "om_tablas_flexibles",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
                {
                    "fieldname": "om_archivos",
                    "label": "Archivos",
                    "fieldtype": "Table",
                    "options": "Orden Manufactura Archivo",
                    "insert_after": "om_section_archivos",
                    "depends_on": SUBCONTRACT_DEPENDS,
                },
            ]
        },
        ignore_validate=True,
        update=True,
    )

    frappe.clear_cache(doctype="Purchase Order")
